name: mar
description: A library for dealing with MAR (Much Assembly Required) source code.
author: Ethan Lafrenais

publish_to: none

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  charcode: ^1.1.2
  meta: ^1.1.6
